name: CI
on:
  pull_request: {}
  push: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9-dev, pypy3]
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Install dependencies on ubuntu
      - if: matrix.os == 'ubuntu-latest'
        name: Install build dependencies
        run: sudo apt-get install -y libxml2-dev libxslt-dev

      # Install 32-bit windows target for pypy3
      - if: matrix.os == 'windows-latest' && matrix.python-version == 'pypy3'
        name: Install 32-bit Rust target
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: i686-pc-windows-msvc

      - name: Build package
        run: pip install -e .

      - name: Test tomlgen_rust
        shell: bash
        run: |
          pip install wheel
          cd example_tomlgen
          python setup.py tomlgen_rust -w build
      # FIXME: Can't test easily on windows 3.9 or pypy because have to build lxml from source!
      - name: Test html-py-ever
        if: ${{ !(matrix.os == 'windows-latest' && (matrix.python-version == 'pypy3' || matrix.python-version == '3.9-dev')) }}
        shell: bash
        run: |
          cd html-py-ever
          pip install -r requirements-dev.txt
          python setup.py install
          cd test && pytest
      - name: Test other examples
        shell: bash
        run: |
          cd examples/
          # PEP517 build isolation means we don't use the setuptools-rust locally,
          # instead it installs from PyPI!
          pip install --no-use-pep517 -e rust_with_cffi/
          pip install -r rust_with_cffi/requirements-dev.txt
          pytest rust_with_cffi/tests.py
